### PR TITLE
2 feature 2 user preferencediscovery

### PR DESCRIPTION
**Pull request by Caconoutt**
The preference discovery feature functions correctly and passes a simple dummy user test. 
Users can discover other users by using the preference feature.

### CODE REVIEW

**Review by Christina0313 — APPROVED** [review]
Code is reviewed and approved by Christina. The preference discovery includes the common function used by all three types of discovery which is very useful for implementing the search discovery feature. The Java doc added are good and overall the feature follows clean architecture.

**Review by Jennifer-xxx — APPROVED** [review]
This pull request is reviewed and approved by Jennifer Liu. The preference discovery feature is well implemented based on clean architecture. The use of a database also shows the overall data persistence. The result of the program fulfills the expectation. The tests are well-written and all pass. Well done! Perhaps more tests can be added later to ensure that everything is going on the right track.

**Review by Christina0313 — DISMISSED** [review]
Code is reviewed and approved by Christina Lan. The preference discovery includes the common function used by all three types of discovery which is very useful for implementing the search discovery feature. The Java doc added are good and overall the feature follows clean architecture. The test changes works well.

**Review by Jennifer-xxx — APPROVED** [review]
This overall looks good from my end. Same comments and suggestions as before!

**Review by Christina0313 — APPROVED** [review]
Code is reviewed and approved by Christina Lan. The test changes works well and it is useful to help test the interactor. Good for merge now.

**Review by imamberr — APPROVED** [review]

**Pull request merged**
