### PR TITLE
4 feature 3 user searchdiscovery

### PR DESCRIPTION
**Pull request by Christina0313**
New Info page is added for the discovery user. Now it displays user's name, age, hobby and relationship type.

### CODE REVIEW

**Review by Caconoutt — DISMISSED** [review]
A new info page was developed on top of the current files, which reduces duplication. Clean architecture has been followed. Looks good on my end. Ready to merge!

**Review by alyssamyli — APPROVED** [review]
This pull request is reviewed and approved by Alyssa. Added docstring provides a better explanation of the test functionality.

**Review by Jennifer-xxx — APPROVED** [review]
This pull request is reviewed and approved by Jennifer. This change follows the overall structure of the project and is written based on clean architecture. The addition of information on the user info page follows my suggestion conforms with our general design direction and makes the result page more clean and informational. It is ready to merge. Well done!

**Review by alyssamyli — APPROVED** [review]
The pull request is reviewed and approved by Alyssa, the overall coding style and program structure satisfies SOLID principle and Clean architecture. The newly added docstring provides some information about how the test is implemented and its functionality. Well done!! ready to merge

**Review by zzy620 — APPROVED** [review]
The code is reviewed and approved. The updated user info page perfectly combines each part. And the overall structure follows the clean architecture and facade design pattern well.

**Pull request merged**
