### PR TITLE
3 feature 4 user login and signup feature

### PR DESCRIPTION
**Pull request by sumiyuan**
GUI workflow working, signup and login have data persistance writing to currentUser.csv, and user.csv.
User is able to login if they have an account, or to signup if they don't have an account.

### CODE REVIEW

**Review by alyssamyli — APPROVED** [review]
Great design for user entity which brings convenience for implementing our feature.

**Review by Christina0313 — APPROVED** [review]
The overall User feature is great! It allows user the enter the app and set up their information which can be used in the discovery part later. The csv file produce data persistence. The idea of Clean architecture is also shown in the code. Great work!

**Review by zzy620 — APPROVED** [review]
Looks Great! Methods in entities help me quickly get the user info I need in my use case.

**Review by Jennifer-xxx — APPROVED** [review]
This pull request is reviewed and approved by Jennifer. 
Great implementation of the User Login and Signup feature! Finished the task well, Used the proper clean architecture, and provided enough methods for me to implement the chat feature later.

**Comment by imamberr** [comment]
The User feature is fully functional. User is an important part which helps me to implement my feature.

**Comment by yumozi** [comment]
This branch is an important use case that many other use cases require, so it was definitely good to prioritize merging this into main as quickly as possible. There are some temporary workarounds in the UI layer, including the addition of MainFrameInterface, that need to be updated eventually, but since they don't affect the use cases they can be ignored for now.

**Pull request merged**
