### PR TITLE
4 feature 3 user searchdiscovery

### PR DESCRIPTION
**Pull request by Christina0313**
New Tests are added for Search Discovery. All the warnings are fixed.

### CODE REVIEW

**Review by sumiyuan — DISMISSED** [review]
Good job adding tests and removing unneccessary imports

**Review by yumozi — DISMISSED** [review]
LGTM!

**Review by Jennifer-xxx — APPROVED** [review]
Good job fixing the warnings and adding useful tests!

**Review by alyssamyli — APPROVED** [review]
LGTM

**Review by sumiyuan — APPROVED** [review]
Looks good to me, added insightful docstrings

**Review by imamberr — APPROVED** [review]
This pull request is reviewed and approved by Amber. The tests are well written and all pass. All warnings are fixed. It's ready to merge

**Pull request merged**
