### PR TITLE
8 feature 8 chat test

### PR DESCRIPTION
**Pull request by alyssamyli**
Unit tests for all entities and use cases are added with docstring explanation of what is the test implementing and how is it implemented.

### CODE REVIEW

**Review by imamberr — APPROVED** [review]
This pull request is reviewed and approved by Yaqi Liu. Everything looks good and ready to merge.

**Review by Jennifer-xxx — APPROVED** [review]
This pull request is reviewed and approved by Jennifer Liu. The tests are well-written and cover a wide range of classes in the chat feature. The slight modification to the implementation of the feature is very useful. Well done!

**Review by Caconoutt — APPROVED** [review]
This pull request is checked and approved by Camilla. The modification looks good on my end and clean architecture has been followed. Javadoc has been added to allow readers to understand easily. Ready to merge!

**Review by Christina0313 — APPROVED** [review]
This pull request is checked and approved by Christina. The chat test added helps ensure everything works well. Seems good to merge

**Pull request merged**
