### PR TITLE
6 feature 6 user blocklist

### PR DESCRIPTION
**Pull request by imamberr**
Modified the test format

### CODE REVIEW

**Review by Christina0313 — DISMISSED** [review]
The changes looks good to me.

**Review by Caconoutt — DISMISSED** [review]
Changes look good to me, good to go!

**Review by Christina0313 — APPROVED** [review]
The changes looks good to me.

**Review by alyssamyli — APPROVED** [review]
LGTM

**Review by Caconoutt — APPROVED** [review]
lgtm

**Pull request merged**
