### PR TITLE
Fixed test modifying database issue

### PR DESCRIPTION
**Pull request by yumozi**
Fixed the issue that would allow junit test to modify database.

### CODE REVIEW

**Review by sumiyuan — DISMISSED** [review]
LGTM!

**Review by Christina0313 — DISMISSED** [review]
The warning is resovled and the test are modified.Ready to merge

**Review by Christina0313 — APPROVED** [review]
All warning is fixed. Looks good to me

**Review by imamberr — APPROVED** [review]
fixed warning and modified test. It's ready to merge!

**Pull request merged**
