### PR TITLE
Fixed path setting for csvManager

### PR DESCRIPTION
**Pull request by sumiyuan**
Changed the path setting for csvManager to a private final String, to make understanding the code easier and make a constant path non accessable to classes.

### CODE REVIEW

**Review by Christina0313 — APPROVED** [review]
The changed makes understanding the class easier.  Good job!

**Review by Jennifer-xxx — APPROVED** [review]
This pull request is reviewed and approved by Jennifer. This is a very useful and important change that can greatly help increase the readability of the code and the effectiveness of calling the function. This maintains the overall structure of the project and makes it easier for me to call the current user.

**Comment by Caconoutt** [comment]
This pull request is reviewed and approved by Camilla. Changes have been made to multiple files that allow the structure to be more clear. More importantly, in the file csvManager, methods have been updated so that they could be called in the use case class from my feature easily. The changes are the results of the discussion from Monday 207 Lab.

**Review by Caconoutt — APPROVED** [review]
This pull request is reviewed and approved by Camilla. Changes have been made to multiple files that allow the structure to be more clear. More importantly, in the file csvManager, methods have been updated so that they could be called in the use case class from my feature easily. The changes are the results of the discussion from Monday 207 Lab.

**Pull request merged**
