### PR TITLE
Added new test cases, and fixed overwriting frame size

### PR DESCRIPTION
**Pull request by sumiyuan**
Added test cases for use case, user factory, and the controllers. Alongside fixed clean architecture problem with constant rewriting of page width and height

### CODE REVIEW

**Review by Christina0313 — DISMISSED** [review]
The warning is fixed and the test is added. Seems good to me

**Review by yumozi — DISMISSED** [review]
LGTM!

**Review by alyssamyli — APPROVED** [review]
LGTM!

**Review by Christina0313 — DISMISSED** [review]
Everything looks good

**Review by yumozi — APPROVED** [review]
LGTM!

**Review by Christina0313 — APPROVED** [review]
everything looks fine

**Review by Jennifer-xxx — APPROVED** [review]
Good changes!

**Pull request merged**
