### PR TITLE
Updated User, UserResponseModel, UserRequestModel, and csvManager

### PR DESCRIPTION
**Pull request by sumiyuan**
Added docstring to user use case, user entity, controllers and UI elements.

### CODE REVIEW

**Comment by sumiyuan** [comment]
added docstrings, Updated User, UserResponseModel, UserRequestModel, and csvManager to remove conflicts and errors. While allowing easier access to user information within the responseModel, and requestModel.

**Review by Christina0313 — CHANGES_REQUESTED** [review]
For the sexual orientation, can you please change it to "male" "female" or "bisexual"? The other change made are very helpful in implementing the search discovery. As the area of interest is put into the response model, it is easier to access. Thank you! There are some information type error like the "petOp" should be boolean.  No need to change that, I'll change my interactor based on it to make it work

**Comment by Caconoutt** [comment]
The **getInterestRank()** method in UserResponseModel should return List<String> instead of String. 
To explain, the variable interestRank stores the information on how users rank the importance of 6 characteristics(income, interest, age, pet, marital status, relationship type). **interestRank is NOT interest.** 
Correspondingly, the CSV files user and currentUser need to be modified.

**Review by Caconoutt — CHANGES_REQUESTED** [review]
The getInterestRank() method in UserResponseModel should **return List instead of String**.
To explain, the variable interestRank stores the information on how users rank the importance of 6 characteristics(income, interest, age, pet, marital status, relationship type). interestRank is NOT interest.
Correspondingly, the CSV files user and currentUser need to be modified.

**Review by yumozi — DISMISSED** [review]
Everything seems good on my end. It can probably be merged after the changes requested by other reviewers has been made.

**Review by Christina0313 — DISMISSED** [review]
The updated version satisfied what we need for the discovery part. The csv interface added follows the clean architecture.

**Review by Caconoutt — APPROVED** [review]
This pull request is checked and approved by Camilla. The files have been updated corresponding to the request before. The interface added follows the clean architecture, specifically, the interaction between the use case and database. It allows my feature to access information easily.

**Review by yumozi — APPROVED** [review]
The changes that were requested were made. Ready for merge.

**Review by yumozi — APPROVED** [review]
The changes that were requested were made. Ready for merge.

**Pull request merged**
